# Generated by Django 3.2.21 on 2023-10-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address_1', models.CharField(max_length=250)),
                ('street_address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=250)),
                ('county', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(default='Germany', max_length=250)),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('pick_and_collect', models.BooleanField(default=False)),
                ('delivery_costs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
