# Generated by Django 3.2.21 on 2023-10-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pick_and_collect',
            new_name='click_and_collect',
        ),
    ]
