# Generated by Django 3.2.21 on 2023-10-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_pick_and_collect_order_click_and_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='click_and_collect',
        ),
    ]
