# Generated by Django 3.2.21 on 2023-10-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231019_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type', 'date_of_event']},
        ),
    ]
